    # Made by Eduardo 04/13/26
upstream backend_pool {
    server 100.100.135.97;
    server 100.87.44.64 backup;
}


server {
    listen 443 ssl;
    server_name 100.71.114.73;

    ssl_certificate /etc/ssl/certs/apache-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/apache-selfsigned.key;

    location / {
        proxy_pass http://backend_pool;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
