#ainesh - 3/31/26
#holds users, ips, and directories for every vm
FE_USER="vboxuser"
FE_IP="100.100.135.97"
FE_PATH="/home/vboxuser/git/rabbitmqphp_example/frontend"

DMZ_USER='vboxuser'
DMZ_IP="100.117.9.105"
DMZ_PATH="/home/vboxuser/git/rabbitmqphp_example/worker"

DB_USER="backend1"
DB_IP="100.84.167.48"
DB_PATH="/home/backend1/git/rabbitmqphp_example/consumer"
